version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: local_postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: pharma
    volumes:
      - ../../postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"